version: '2.1'

orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.11.1
  working_directory: ~/project

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      pip install --user tox

jobs:
  test_and_upload_regression_model:
    <<: *defaults
    working_directory: ~/project/deploying_with_containers/model_package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Fetch the data
          command: |
            tox -e fetch_data
      - run:
          name: Test the model
          command: |
            tox
      - run:
          name: Publish model to Gemfury
          command: |
            tox -e publish_model

  test_app:
    <<: *defaults
    working_directory: ~/project/deploying_with_containers/houseprice_api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Running app tests
          command: |
            tox

  deploy_app_container_via_railway:
    <<: *defaults
    steps:
      - setup_remote_docker:
          version: edge
      - checkout:
          path: ~/project/
      - node/install:
          node-version: '22.18'
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Build and Dockerfile
          command: |
            cd deploying_with_containers && railway up --detach --service service_ID

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - test_and_upload_regression_model:
          filters:
            branches:
              only:
                - main
                - demo

      - test_app:
          requires:
            - test_and_upload_regression_model
          filters:
            branches:
              only:
                - main
                - demo

      - deploy_app_container_via_railway:
          requires:
            - test_app
          filters:
            branches:
              only:
                - main
                - demo